version: '3.8'
services:
  internetbanking:
    image: pankajsharma72/ib-image:latest
    container_name: ib-container
    ports:
      - "81:80"
    deploy:
      replicas: 3
    volumes:
      - /var/lib/internetbanking
  mobilebanking:
    image: pankajsharma72/mb-image:latest
    container_name: mb-container
    ports:
      - "82:80"
    deploy:
      replicas: 3
    volumes:
      - /var/lib/mobilebanking
  insaurance:
    image: pankajsharma72/ins-image:latest
    container_name: ins-container
    ports:
      - "83:80"
    deploy:
      replicas: 3
    volumes:
      - /var/lib/insaurance
  loans:
    image: pankajsharma72/loans-image:latest
    container_name: loans-cont
    ports:
      - "84:80"
    deploy:
      replicas: 3
    volumes:
      - /var/lib/loan
